//console.log(a);
/*
console.log(b);

let a=10;
var b=20;

c();
//function declaration is fully hoisted
function c() {
 console.log("I am function C");   
}

//d();
//function expression is not hoisted
let d=function(){
  console.log("I am function D");  
}

*/
//var is partially hoisted



console.log(y);

let x=function(){
   console.log("I am x"); 
}
var y=function(){
   console.log("I am y"); 
}
//x();


























